logging:
  level: INFO
  loggers:
    zone.gryphon: ${var!'DEBUG'}

  appenders:
    - type:        console
      logFormat:   '[%date{"yyyy-MM-dd'' ''HH:mm:ss,SSS XXX",CST}]\(%t\) %p - %logger{0} - %m%n%rEx'

geminos:
  rootFolder: 'CHANGEME'